version: '3.1'

services:

  adminer:
    image: adminer
    restart: "no"
    ports:
      - ${ADMYNER_PORTS}

  db-concesionario:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORTS}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
